version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB: chartgram
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"