package chartgram.charts.model;

public enum ChartType {
	MESSAGES_WITH_RESPECT_TIME,
	MESSAGES_DISTRIBUTION_BY_TYPE,
	JOIN_DISTRIBUTION_RESPECT_TIME,
	LEAVINGS_DISTRIBUTION_RESPECT_TIME,
	JOINS_VS_LIVINGS
}
